### PR TITLE
Update to latest versions

### PR DESCRIPTION
**Pull request by ejc123**
Updated Dockerfile to the latest Erlang 25.2.3.0 image

Updated dependencies:
Replaced `rebar3_lfe_compile` with `rebar3_lfe` (0.4.3) as the former was deprecated and points to the latter
Updated `ltest` to latest version 0.13.3
Updated `lfe` to latest version 2.1.1

All of the dependencies are available from hex.

I had to modify the `expected_results.json` files due to minor changes in the output.  Things still passed/failed as expected.  I also added a 'description' to each of the `.app.src` files to quiet a compiler warning.

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
Nice! Could you maybe also add a new test case that uses the old setup to see if that still works?

**Comment by ejc123** [comment]
I tried, but the old rebar.config will not work.  There was a breaking change between rebar 3.15.x and 3.16 which breaks the old `lfe-compile` plugin.  
It might be possible to install rebar 3.15.2 in docker, but Erlang versions newer than 19.0 will warn about removed functions that LFE 1.1.1 uses. 
Not sure about the best path forward.

**Comment by ErikSchierboom** [comment]
Okay, then I would propose we do the following:

- Before merging this PR, we'll add `rebar.config` to an exercise's `files.invalidator` field in it's `.meta/config.json` file. Once this is merging, changing the `rebar.config` for an exercise will prompt a student to update, which we can then use to do a follow-up PR to update the exercises in the `exercism/lfe` repository to use the latest `rebar.config`. See https://github.com/exercism/scala/pull/735/files for an example of such a PR.
- After merging those two PRs, we can merge this.

**Comment by ejc123** [comment]
That's really slick.  So nothing will change for students until the `rebar.config` changes are pushed?  So `rebar.lock` would be updated in the same commit as `rebar.config`, correct?

**Comment by ejc123** [comment]
PR for adding `rebar.config` to exercise's `files.invalidator` field https://github.com/exercism/lfe/pull/166

**Comment by ErikSchierboom** [comment]
> So nothing will change for students until the rebar.config changes are pushed? 

Well, if they would run their tests without updating their exercise, they would get an error. But they would be able to update their exercise via a simple process.

> So rebar.lock would be updated in the same commit as rebar.config, correct?

Correct!

**Comment by ejc123** [comment]
This PR https://github.com/exercism/lfe/pull/163 will update all the `rebar.config` and `rebar.lock` files.  

The top-level documentation looks pretty good.  There's a reference to a docker image in `INSTALLATION.md` which doesn't work for me, but I'm not sure if that's my setup or that it is 6 years old. 
Would it be a good idea to remove this reference until an updated image is available?

**Comment by ErikSchierboom** [comment]
> The top-level documentation looks pretty good. There's a reference to a docker image in INSTALLATION.md which doesn't work for me, but I'm not sure if that's my setup or that it is 6 years old.
Would it be a good idea to remove this reference until an updated image is available?

I think so.

**Comment by ejc123** [comment]
I updated `INSTALLATION.md` so exercism/lfe#163 is ready to go.  Let me know if there are any other things that need to happen before these changes can be merged.
Otherwise I'll just let you merge things at your convenience.

**Pull request merged**
