### PR TITLE
LFE 2.1.1 to 2.1.3

### PR DESCRIPTION
**Pull request by BNAndras**
This bumps the LFE version and also puts us on the current Erlang version. Once this is approved, I'll update the rebar configs in the main LFE track repo. I'm hoping this might fix the occasional CI breakage in the LFE repo as well.

### CODE REVIEW

**Comment by BNAndras** [comment]
This repo is giving me an option to merge without a required review. I think that needs to be fixed as well.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
I've added a branch protection rule.

**Comment by BNAndras** [comment]
2.1.4 is available for download from source, but it's not actually in Hex so I'm going with 2.1.3. The expected results apparently didn't need to be updated after I ran the run-tests-in-docker script

**Comment by BNAndras** [comment]
./bin/run-tests-in-docker.sh runs fine locally so I'm not sure yet why the CI complains here.

**Comment by ErikSchierboom** [comment]
Hmmm, `./bin/run-tests-in-docker.sh` failed for me locally. I've pushed a commit to fix it.

**Pull request merged**
